[package]
name = "protocol"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
ts-rs = { version = "10.1.0", features = ["serde-json-impl", "serde-compat"] }

[features]
multi-tenant = []
