[package]
name = "ember-link"
version = "0.1.0"
edition = "2021"

[dependencies]
automerge = "0.5.12"
automerge_repo = { version = "0.2.0", features = ["tokio"] }
futures-util = "0.3.31"
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["full"] }
tokio-tungstenite = "0.26.0"
uuid = { version = "1.11.0", features = ["v4"] }


protocol = { path = "../../packages/protocol" }