[package]
name = "ember-link"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
envconfig = "0.11.0"
futures-util = "0.3.31"
nohash-hasher = "0.2.0"
parking_lot = "0.12.3"
protocol = { path = "../../packages/protocol" }
ractor = "0.14.7"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["full"] }
tokio-tungstenite = "0.26.0"
uuid = { version = "1.11.0", features = ["v4"] }
